<?php

namespace TicketBundle\Repository;

/**
 * TicketEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
