<?php

namespace CommentBundle\Repository;

/**
 * CommentEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
